services:
  postgres:
    image: postgres:18
    container_name: shortener-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - shortener_postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  flyway:
    image: flyway/flyway:12-alpine
    container_name: shortener-flyway-migration
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../database/migration:/flyway/sql
    command: -url=jdbc:postgresql://postgres:5432/shortener -user=postgres -password=postgres migrate

  redis:
    image: redis:8.6-alpine
    container_name: shortener-redis_cache
    ports:
      - "6379:6379"

  keycloak:
    image: keycloak/keycloak:26.6
    container_name: keycloak-dev
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_HTTP_PORT: 8180
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"

      KC_DB: dev-file

      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "false"

    ports:
      - "8180:8180"
      - "9000:9000"

    healthcheck:
      test: [ "CMD-SHELL", "curl --head -fsS http://localhost:9000/health/ready | echo $?" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - shortener_keycloak_data:/opt/keycloak/data

  shortener:
    profiles:
      - full
    image: shortener:${SHORTENER_VERSION}
    container_name: shortener-app
    build:
      context: ../shortener
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      redis:
        condition: service_started
      keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      BASE_DOMAIN: http://localhost:8080
      SPRING_PROFILES_ACTIVE: prod
      DB_USER: postgres
      DB_PASSWORD: postgres
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/shortener
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8180/realms/shortener/protocol/openid-connect/certs

  cleanup-cron:
    profiles:
      - full
    image: alpine:3.23
    container_name: cleanup-cron
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - ./cleanup-cron-setup.sh:/cleanup-cron-setup.sh
      - ./cleanup-cron-task.sh:/cleanup-cron-task.sh
    command: sh /cleanup-cron-setup.sh
    restart: unless-stopped
    environment:
      KEYCLOAK_URL: http://keycloak:8180
      SHORTENER_URL: http://shortener:8080
      CRON_CLIENT_ID: shortener-cron
      CRON_CLIENT_SECRET: cron-secret

volumes:
  shortener_postgres_data:
  shortener_keycloak_data:
