services:
  postgres:
    image: postgres:18
    container_name: shortener-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - shortener_postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  flyway:
    image: flyway/flyway:12-alpine
    container_name: shortener-flyway-migration
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../database/migration:/flyway/sql
    command: -url=jdbc:postgresql://postgres:5432/shortener -user=postgres -password=postgres migrate

volumes:
  shortener_postgres_data:
