short-link:
  cache-default-timeout: 1d
  base-domain: http://localhost:8080
server:
  http2:
    enabled: true
spring:
  application:
    name: reactive-url-shortener
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shortener
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/shortener
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    persist-authorization: true
    display-request-duration: true
    oauth:
      client-id: shortener-client
      realm: shortener
      app-name: "Url Shortener API"
      use-pkce-with-authorization-code-grant: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
